name: CI/CD

on:
  push:
    branches: 
      - master
      - release
  pull_request:
    branches: 
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: [HotelInformationAPI, RoomReservationAPI, UserRegistrationAPI] # Les noms des dossiers ou des projets pour chaque API

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Utilisation de .NET 8

    - name: Install dependencies
      run: dotnet restore HotelBookingSystemSolution.sln # Restaurer les dépendances pour la solution entière

    - name: Build
      run: dotnet build HotelBookingSystemSolution.sln --no-restore # Construire la solution entière

    - name: Run tests
      run: dotnet test HotelBookingSystemSolution.sln --no-build --verbosity normal # Exécuter les tests pour la solution entière

    - name: Publish API
      run: |
        for api in HotelInformationAPI RoomReservationAPI UserRegistrationAPI; do
          echo "Publishing $api..."
          dotnet publish $api/$api.csproj -c Release -o $api/publish
        done

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: published-apis
        path: |
          HotelInformationAPI/publish
          RoomReservationAPI/publish
          UserRegistrationAPI/publish

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Download Artifacts
      uses: actions/download-artifact@v3
      with:
        name: published-apis
        path: ./ # Téléchargez les artifacts à la racine

    - name: Publish to Azure
      env:
        AZURE_WEBAPP_NAME: clean-architecture 
        AZURE_RESOURCE_GROUP: clean-archi
        AZURE_PUBLISH_PROFILE: ${{ secrets.TEST_SECRET }} # Assurez-vous d'ajouter votre profil de publication en tant que secret GitHub
      run: |
        for api in HotelInformationAPI RoomReservationAPI UserRegistrationAPI; do
          dotnet publish $api/$api.csproj -c Release -o $api/publish
          az webapp deploy --name $AZURE_WEBAPP_NAME --resource-group $AZURE_RESOURCE_GROUP --src-path $api/publish
        done
