name: CI/CD

on:
  push:
    branches: 
      - master
      - release
  pull_request:
    branches: 
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api: [HotelInformationAPI, RoomReservationAPI, UserRegistrationAPI]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x'

    - name: Install dependencies
      run: dotnet restore HotelBookingSystemSolution.sln

    - name: Build
      run: dotnet build HotelBookingSystemSolution.sln --no-restore

    - name: Run tests
      run: dotnet test HotelBookingSystemSolution.sln --no-build --verbosity normal

    - name: Publish API
      run: |
        for api in HotelInformationAPI RoomReservationAPI UserRegistrationAPI; do
          echo "Publishing $api..."
          dotnet publish $api/$api.csproj -c Release -o $api/publish/$api
          echo "Published $api to $api/publish/$api"
        done

  release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Upload Release Assets - HotelInformationAPI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: HotelInformationAPI/publish/HotelInformationAPI
        asset_name: HotelInformationAPI.zip
        asset_content_type: application/zip

    - name: Upload Release Assets - RoomReservationAPI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: RoomReservationAPI/publish/RoomReservationAPI
        asset_name: RoomReservationAPI.zip
        asset_content_type: application/zip

    - name: Upload Release Assets - UserRegistrationAPI
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TEST_SECRET }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: UserRegistrationAPI/publish/UserRegistrationAPI
        asset_name: UserRegistrationAPI.zip
        asset_content_type: application/zip
